---
# Bring Down stack
- hosts: loadbalancer
  sudo: true
  tasks:
    - service: name=nginx state=stopped
    
- hosts: webserver
  sudo: true
  tasks:
    - service: name=apache2 state=stopped
    
# restart mysql
- hosts: database
  sudo: true
  tasks:
    - service: name=mysql state=restarted

# Bring stack up
- hosts: webserver
  sudo: true
  tasks:
    - service: name=apache2 state=started

- hosts: loadbalancer
  sudo: true
  tasks:
    - service: name=nginx state=started